### PR TITLE
Update zh-simplified.yml

### PR DESCRIPTION
**Pull request by SnowCutieOwO**
I've been added some missing changes, if anything still not right, please reply me in the pull request. Thanks <3

### CODE REVIEW

**Comment by Sytm** [comment]
Thank you very much for updating the translation file <3

**Comment by SnowCutieOwO** [comment]
> Thank you very much for updating the translation file <3

Since it got updated, please change the status in Modrinth. Thanks :3

**Comment by Sytm** [comment]
I changed the description on Modrinth, if that is what you meant.

But I actually messed up while adding one feature and forgot to copy these two values to the chinese translations:
https://github.com/Sytm/waypoints/blob/v4%2Fmaster/waypoints%2Fsrc%2Fmain%2Fresources%2Flang%2Fzh-simplified.yml#L212

https://github.com/Sytm/waypoints/blob/v4%2Fmaster/waypoints%2Fsrc%2Fmain%2Fresources%2Flang%2Fzh-simplified.yml#L519
It would be nice if you could translate them aswell

**Comment by SnowCutieOwO** [comment]
> I changed the description on Modrinth, if that is what you meant.
> 
> But I actually messed up while adding one feature and forgot to copy these two values to the chinese translations: https://github.com/Sytm/waypoints/blob/v4%2Fmaster/waypoints%2Fsrc%2Fmain%2Fresources%2Flang%2Fzh-simplified.yml#L212
> 
> https://github.com/Sytm/waypoints/blob/v4%2Fmaster/waypoints%2Fsrc%2Fmain%2Fresources%2Flang%2Fzh-simplified.yml#L519 It would be nice if you could translate them aswell

https://github.com/Sytm/waypoints/pull/113
Got it. :)

**Pull request merged**
